### PR TITLE
Show Nextcloud version

### PR DESCRIPTION
**Pull request by phsc84**
Fix for #4.

Plus little adjustements of the welcome text. But I can revert these adjustements, if you don't like it.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Not sure if we want external HTTP requests, O thought everything should be self-contained @MorrisJobke?

**Comment by MorrisJobke** [comment]
> 1 additional HTTP request necessary

Yes. It would be nice to have it as self contained as possible. No need to remove the inline image. Because then other problems could occur and this only saves for exact 1 request (usually you don't install nextcloud 10x a day ;)).

**Comment by MorrisJobke** [comment]
@phsc Could I ask you to remove the change of the image. In general it is easier to have separate pull requests for different changes.

The other change looks good

**Comment by phsc84** [comment]
Thank you for your feedback. I will adjust my pull request later this week.
And I have to figure out, how I can create multiple pull requests for the same repository...

**Comment by MorrisJobke** [comment]
> And I have to figure out, how I can create multiple pull requests for the same repository...

You can create git branches and each branch could then be the base of a pull request.

**Pull request closed without merging**
