### PR TITLE
Bump to 14.0.0

### PR DESCRIPTION
**Pull request by gratuxri**
Just update to 14.0.0 (tested local)

### CODE REVIEW

**Comment by jospoortvliet** [comment]
I'd say we should move to 14.0.1, that should be more than ready for new users! @MorrisJobke agreed?

**Comment by MorrisJobke** [comment]
> I'd say we should move to 14.0.1, that should be more than ready for new users! @MorrisJobke agreed?

Yes - let me do the 14.0.1 thing. 

@gratuxri Thanks for the update anyways 👍

**Comment by MorrisJobke** [comment]
731110c

**Comment by MorrisJobke** [comment]
Deployed as well.

**Pull request closed without merging**
