### PR TITLE
Set Nextcloud version to 10.0.1

### PR DESCRIPTION
**Pull request by phsc84**
Supersedes #7 (sorry, still playing around with Git)

### CODE REVIEW

**Comment by phsc84** [comment]
@MorrisJobke 
Please review :-)

**Comment by phsc84** [comment]
Btw:
How does the upload of "setup-nextcloud.php" from the Github repo to the nextcloud.com homepage work? Is this a daily job or a manual task?

**Comment by MorrisJobke** [comment]
> Is this a daily job or a manual task?

Manual task ;)

**Comment by MorrisJobke** [comment]
But 10.0.1 is not yet released ;) But thanks anyway

**Comment by phsc84** [comment]
Now 10.0.1 has already been released a few days ago. My 10.0.1 installation - of course with the web-installer - was very smooth.
So, I think it should be ready to merge.

**Comment by LukasReschke** [comment]
Changes deployed, thank you @phsc 🚀

**Pull request merged**
